### ISSUE TITLE
Duplicated text content due to misuse of the wholeText property

### ISSUE THREAD

**Issue by njordhov** [clj-commons/hickory#34]
Both `hickory.core/as-hiccup` and  `hickory.core/as-hickory` use DOM's [wholeText](https://www.w3.org/TR/dom/#dom-text-wholetext) property to extract the text value of a dom node. However, instead of just returning the text content of a node, this property concatenates all Text nodes logically adjacent to the node. 

This may lead to unexpected results, particularly when a parsed document is modified before converting it into hiccup or hickory. Transpiling [a mozilla example of using wholeText](https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText):

```
(def doc (hickory.core/parse "<p>Thru-hiking is great! <strong>No insipid election coverage</strong> However, <a href=\"http://en.wikipedia.org/wiki/Absentee_ballot\">casting a ballot</a> is tricky.</p>"))
(def para (.item (.getElementsByTagName doc "p") 0))
(.removeChild para (.item (.-childNodes para) 1))
```

After the removal of the _strong_ element from the paragraph `(as-hiccup para)` now returns:

```
[:p {} "Thru-hiking is great!  However, " "Thru-hiking is great!  However, " 
  [:a {:href "http://en.wikipedia.org/wiki/Absentee_ballot"} "casting a ballot"] " is tricky."]
```

Notice the duplicate text caused by wholeText concatenating adjacent text nodes for the two text nodes remaining after removing the originally interjecting _strong_ element.

A fix is to call [`goog.dom/getRawTextContent`](https://google.github.io/closure-library/api/namespace_goog_dom.html#getRawTextContent) in place of the _wholeText_ property accessors in hickory.core.

**Comment by danielcompton** [comment]
Fixed by https://github.com/clj-commons/hickory/pull/33
