### ISSUE TITLE
Counterparts of child and descendant for first element in the chain

### ISSUE THREAD

**Issue by vspinu** [clj-commons/hickory#40]
I have asked for this in #23 but I am afraid `has-child` doesn't cut it, so I am re-iterating it as a separate issue.

I would like to be able to get the first element in a chain of descendants. So if elements are `td > tr > input` the following would give me the `td` element:

``` clj
(hs/parent 
   (hs/tag :td)
   (hs/tag :tr)
   (hs/tag :input))
```

Similarly `hs/ancestor` should be the counterpart of `hs/descendant`.

In this regard the api for same level siblings is complete as given by `follow <> precede` and `folow-adjacent <> precede-adjacent`. 

I know about `has-child`, but the above simple snippet becomes:

``` clj
(hs/and
  (hs/tag :td)
  (hs/and
    (hs/tag :tr)
    (hs/has-child 
      (hs/tag :input))))
```

which even in this simple case looks pretty daunting.

**Comment by davidsantiago** [comment]
I'm having a little trouble understanding your issue. But, the counterpart of descendant is has-descendant. The counterpart of child is has-child. All of the selectors are named to be relative to the node you're trying to select. I don't see why (has-child (tag :tr) (tag :input)) doesn't do what you want in that last example. 

(I believe you're having an issue, of course, I'm just trying to explain why I'm not understanding what you're asking).

**Comment by vspinu** [comment]
> I don't see why (has-child (tag :tr) (tag :input)) doesn't do what you want in that last example. 

My last example had one `has-child` missing. 

I guess my main issue is that you need to include `(hs/and (hs/has-child` for every level of hierarchy. Compare:

```clj
(hs/and
  (hs/tag :td)
  (hs/has-child
    (hs/and
      (hs/tag :tr)
      (hs/has-child 
        (hs/tag :input)))))
```
vs
```clj
(hs/parent
  (hs/tag :td) 
  (hs/tag :tr)
  (hs/tag :input))
```

I don't see `has-child` as natural counterpart of `child` because it accepts one selector but `child` accepts many. `child` is like a convenient threading macro but `has-child` is not.  A currently missing function `has-parent` would be a natural counterpart of `has-child`.

**Comment by port19x** [comment]
`has-child` is indeed ergonomic and no fun to use!

**Comment by Mertzenich** [comment]
If I have time I hope to implement functional variants of `parent` and `ancestor` (I'll submit a PR if I end up getting around to it). In the meantime, here is a macro I whipped up to produce the has-child/has-descendent chains described above by @vspinu. It takes a function you want to utilize, such as `has-child`, followed by your selectors:

```clojure
(defmacro has-*
  [sel & selectors]
  (if (= (count selectors) 1)
    (list sel (first selectors))
    (let [rev (reverse selectors)]
      (loop [sels (rest rev)
             output (first rev)]
        (cond
          (empty? sels) output
          :else (recur (rest sels)
                       (list hickory.select/and (first sels)
                             (list sel output))))))))
```

Example usage:

```clojure
(macroexpand '(has-* hickory.select/has-child))
;; => nil
```

```clojure
(macroexpand '(has-* hickory.select/has-child (sel/tag :td)))
;; => (hickory.select/has-child (sel/tag :td))
```

```clojure
(macroexpand '(has-* hickory.select/has-child (sel/tag :td) (sel/tag :tr)))
;; => (#function[hickory.select/and]
;;     (sel/tag :td)
;;     (hickory.select/has-child (sel/tag :tr)))

```

```clojure
(macroexpand '(has-* hickory.select/has-child (hs/tag :td) (hs/tag :tr) (hs/tag :input)))
;; => (#function[hickory.select/and]
;;     (hs/tag :td)
;;     (hickory.select/has-child
;;      (#function[hickory.select/and]
;;       (hs/tag :tr)
;;       (hickory.select/has-child (hs/tag :input)))))
```

**Comment by Mertzenich** [comment]
I believe I have a functional solution, I hope to test it sometime this weekend or early next week. It works similarly to the examples above, except this time we recursively combine the functions. I also need to dig into the code base a bit more since I worry that my solution may be reinventing the wheel a bit. I'll post more details as soon as I can.
