### ISSUE TITLE
Close pull requests that won't be merged

### ISSUE THREAD

**Issue by ricardojmendez** [clj-commons/hickory#43]
As a suggestion, having pull requests open for years that have neither been merged nor closed gives the impression that the project might be abandoned, and could discourage future pull requests (fwiw, it almost stopped me).

I'd recommend reviewing the older ones and deciding if you want to keep them open, particularly if they haven't had any activity in a while.

**Comment by davidsantiago** [comment]
Yeah, Maybe you're right. My feeling has always been that they're there if the original requester wants to pick it back up, or if someone else wants to come along and do the work.

**Comment by ricardojmendez** [comment]
> or if someone else wants to come along and do the work.

I'd say that's a reasonable expectation if it's an issue, but for a PR, either it's merged or it isn't. If someone's considering submitting a new one, and they see PRs open from 2014 in 2017, it gives the impression the project's not following up.

How about adding a note to see if the submitter wants to bring them up to speed, and otherwise just close them after X time of radio silence?

**Comment by TerjeNorderhaug** [comment]
As a contributor, I second that more feedback would be helpful. It seemed that my PR #33 was on track to be merged, but it has been in limbo for a while even if the PR would remove a bottleneck for using hickory dependents on Node.

**Comment by port19x** [comment]
100% agree with the sentiment, will work on it

**Comment by port19x** [comment]
Not sure how to proceed with #35, but it's plausible enough to leave open
