### ISSUE TITLE
License Issue with codox - GPLv3 vs EPL

### ISSUE THREAD

**Issue by ckirkendall** [clj-commons/hickory#53]
Can we move codox-klipse-theme to a dev dependency so it isn't part of runtime decencies.  Right now it has GPLv3 license and that has some ramification for anyone using this in proprietary software that EPL doesn't not have.  

https://github.com/viebel/codox-klipse-theme/blob/master/LICENSE

**Comment by davidsantiago** [comment]
Whoa, did not realize that had happened. Happy to get rid of that entirely. Patch welcome.

**Comment by viebel** [comment]
@ckirkendall I am the author of codox-klipse-theme. What license would fit your needs?

**Comment by alesguzik** [comment]
@viebel Apache would be the best, MIT or BSD are great too.
