### ISSUE TITLE
Node.js support revisited

### ISSUE THREAD

**Issue by euporos** [clj-commons/hickory#58]
Pull request #33 allegedly solved the compatibility issues with Node.js. The Readme, however, still states that Hickory “won't work out of the box on node”. I've been reading the heck out of anything related to the issue here, but haven't found any reproducible steps to make hickory load and parse on Node.js.

In case there is currently no sensible way to use hickory on Node.js, maybe there is a perspective to tap into [posthtml-parser](https://github.com/posthtml/posthtml-parser), a Node.js library that outputs something that is almost hickory format. I've elaborated on this solution to HTML-parsing on Node.js [here (SO)](https://stackoverflow.com/questions/59312825/clojurescript-hickory-on-nodejs-parse-html-to-hiccup/63743059#63743059)

I'd be willing to attempt such an integration myself, but would want to make sure that there is indeed no proper solution as of this point (Also, this would be my very first pull request, so I'm a bit daunted and quite unsure if I could actually get it done).

**Comment by Stvad** [comment]
Hey @euporos I was wondering if you've ended up doing any work on this?

**Comment by slipset** [comment]
Closing this now as #33 is merged
