### ISSUE TITLE
Invalid output by as-hiccup

### ISSUE THREAD

**Issue by akond** [clj-commons/hickory#63]
```
(let [data "<root><link>abc</link><link>def</link></root>"]
	(h/as-hiccup (h/parse data)))
```
gives me 
```
([:html {} [:head {}] [:body {} [:root {} [:link {}] "abc" [:link {}] "def"]]])
```
when i should expect
```
([:html {} [:head {}] [:body {} [:root {} [:link {} "abc"] [:link {} "def"]]]])
```

**Comment by port19x** [comment]
You're using the [link](https://www.w3schools.com/Tags/tag_link.asp) [tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) wrong.
Note that this is an html parser, not a general purpose html parser.
Am I missing something?

**Comment by akond** [comment]
I see.
In this case it's not a bug, I guess.
